spring:
  application:
    name: rvc-user-service
  debug:
    port: ${DEBUG_PORT:9001}
  cloud:
    nacos:
      server-addr: ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)
      username: ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)
      password: ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)
      config:
        file-extension: yaml
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        extension-configs:
          - dataId: authority-api-test.yaml
            refresh: true
            group: DEFAULT_GROUP
      discovery:
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        cluster-name: BJ
        ip: ${SERVER_ADDR:ENC(Y5HcvI+7TfzJVRmAMpYDqR0bwJqzwMzdpQ8RCIr1y2w=)}
  datasource:
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${MYSQL_ADDR:ENC(xMRgIMkkMeGcEa2r7Evzw4AZMCHiDpIGN7ETNEIallJTWSl30aRIZqniNoQpgsujTuur8qAezCXaaNxOYKLvlFQjS7pPoe3oBCz2fFUMRhZ0G2qZG8ZYUnUjnkIZyUWDSbns7no1+8L02z0CP+ghKbPao+l7DolA9lLGx2vUbZY=)}
    username: ${MYSQL_USERNAME:ENC(O0WJdHK10k6bhTSQJbTEGrsBytLKSmRX)}
    password: ${MYSQL_PASSWORD:ENC(xk8u9sk/O8iQp5hULhWtASCPvSC6R5o+AggfXiITFKR7iA8kGncdzw==)}
  redis:
    host: ${REDIS_ADDR:ENC(7+i1abkV1AAW737zy56ZvAWdcUq8AKM0WufHtc+3eqo=)}
    database: 0
    port: ${REDIS_PORT:ENC(vZrw6ItoyBBaKAHqyYi6zzoVUc8BRiM+)}
    password: ${REDIS_PWD:ENC(BWt70dzHaoTtVWtJWZF2c592HJgBHV9CdjwRTcOos/qort27DDnJag==)}
    timeout: 3000ms
  rabbitmq:
    host: ${MQ_ADDR:ENC(EdvVJoPyMDMWlcxJ/dKnRnP6hIH/eyyLo0pHab0HbWE=)}
    port: ${MQ_PORT:ENC(lA59hkbOPGfPYnd/ossrjwfdj1g+QKzy)}
    username: ${MQ_USERNAME:ENC(h4sx/sPEXk8MsDhsWNc1pwGRrxucMNqz)}
    password: ${MQ_PWD:ENC(pnc0ZWw3h49DWEJtygRU79rEw3ZBsvl0NYRTW9CuIPKQDydSRTHRYw==)}
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        prefetch: ${MQ_PREFETCH:5}
        concurrency: ${MIN_CONCURRENCY:5}
        max-concurrency: ${MAX_CONCURRENCY:10}
        acknowledge-mode: manual
    exchange-type: ${EXCHANGE_TYPE:ENC(WUANSPJwXgpu928eZLdjtHxqz08RemFd)}
    pre-command: ${PRE_COMMAND:ENC(nRHKgZnkufKa8nZmJ6MsMjF26vxXrT7mRxmRgSqW6Gs=)}