spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_ADDR:ENC(h9xRlu7jZ2/v7Ijedz96Wx7ISYvkYasXTlIVeKfKNJyXLKW3oc10vzNcLQ3IroscJpC4AbUwOSulW3Rwt52+ytaSnnw6Vs6FWDjNR8S72UZzLJqBPxZ7ryTG2ZHJoqYou5yW7/+McVaZRLatY54LEgG23rU6rW1x)}
    username: ${MYSQL_USERNAME:ENC(O0WJdHK10k6bhTSQJbTEGrsBytLKSmRX)}
    password: ${MYSQL_PASSWORD:ENC(xk8u9sk/O8iQp5hULhWtASCPvSC6R5o+AggfXiITFKR7iA8kGncdzw==)}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: ${REDIS_ADDR:ENC(7+i1abkV1AAW737zy56ZvAWdcUq8AKM0WufHtc+3eqo=)} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:ENC(vZrw6ItoyBBaKAHqyYi6zzoVUc8BRiM+)} # Redis服务器连接端口
    password: ${REDIS_PWD:ENC(BWt70dzHaoTtVWtJWZF2c592HJgBHV9CdjwRTcOos/qort27DDnJag==)} # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: rvc-model-service
  cloud:
    nacos:
      server-addr: ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)
      username: ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)
      password: ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)
      config:
        file-extension: yaml
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
      discovery:
        ip: ${SERVER_ADDR:ENC(pUotBACJVShx/DUJATXrXFNULNpIh4s5QW2yyn7mCoA=)}
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        cluster-name: BJ
  rabbitmq:
    host: ${MQ_ADDR:ENC(EdvVJoPyMDMWlcxJ/dKnRnP6hIH/eyyLo0pHab0HbWE=)} # rabbitMQ的ip地址
    port: ${MQ_PORT:ENC(lA59hkbOPGfPYnd/ossrjwfdj1g+QKzy)} # 端口
    username: ${MQ_USERNAME:ENC(h4sx/sPEXk8MsDhsWNc1pwGRrxucMNqz)}
    password: ${MQ_PWD:ENC(pnc0ZWw3h49DWEJtygRU79rEw3ZBsvl0NYRTW9CuIPKQDydSRTHRYw==)}
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        prefetch: ${MQ_PREFETCH:5}
        concurrency: ${MIN_CONCURRENCY:5}
        max-concurrency: ${MAX_CONCURRENCY:10}
        acknowledge-mode: manual
    exchange-type: ${EXCHANGE_TYPE:ENC(WUANSPJwXgpu928eZLdjtHxqz08RemFd)}
    pre-command: ${PRE_COMMAND:ENC(nRHKgZnkufKa8nZmJ6MsMjF26vxXrT7mRxmRgSqW6Gs=)}
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  httpclient:
    enabled: true
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  client:
    config:
      default:
        connect-timeout: 600000
        read-timeout: 600000
        loggerLevel: full
server:
  port: 9100

page:
  size: ${DEFAULT_SIZE:ENC(247Kmy9z8U5mzJ2r/ZBKAuHF3/cxGaGW)}
  first-comment-size: ${FIRST_COMMENT_SIZE:ENC(RtHVkEg8bCEwtMqRh6B/knAJOi+o1pH/)}
  second-comment-size: ${SECOND_COMMENT_SIZE:ENC(aleeydE6I3CEYesZDCQPtRELxqvU/fYR)}

file:
  logger:
    handler: ${Logger:slf4j}
    enable: true
  image:
    image-file-size: ${IMAGE_FILE_SIZE:ENC(iJ4SBFg1JS8G0zMQ0ysSzpjOTUivPgZa)}
    image-type: ${IMAGE_TYPE:ENC(iJSGa95s7NSA3b9uMLIvCWu67Fp3tdMtUSVQ7VZVRRYsTkiRa9qW+Q==)}
  model:
    model-file-size: ${MODEL_FILE_SIZE:ENC(D5OhrXABwbOUkYYldgY+LWFbu52QxhjK)}
    model-type: ${MODEL_TYPE:ENC(s/b/P1wycc8fmvSEFCZfldt3xy99xZNDqVrl2less4c=)}
  audio:
    audio-type: ${AUDIO_TYPE:ENC(qgyb5bmrlcXsQ44XrEbIlOgksdwArXo2tJfSadByCLRj5YrrRiDVXMZJvCgfMvEn)}
    audio-file-size: ${AUDIO_FILE_SIZE:ENC(/0Nymk2YtBobya24vOgl+vBVp2q6Ly0Y)}

labels:
  allow_labels: ${LABELS:ENC(ZGOcc9GZKPsDfP3fQ4xgMxdUr4FgsQAYKvY5MD6ePaEi/4HkZH5yAQ==)}

mq:
  enable: ${DEFAULT_MQ:rabbit}
assistant:
  service:
    id:
      snowflake:
        startTime: 2023-12-05 00:00:00
        register: register-redis
logging:
  level:
    feign.Logger: debug
