mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${SERVER_PORT:9100}
spring:
  config:
    import: classpath:you-cant-see-that.yml
  profiles:
    active: ${ACTIVE:prod}

